require_relative "mini_erb/version"

# A simplified, streamlined erb replacement.
class MiniErb

  # The Ruby code generated by mini erb.
  attr_reader :src

  # Create a mini_erb object
  def initialize(string, safe_level=nil, _=nil, eoutvar='_erbout')
    @safe_level, @eoutvar = safe_level, eoutvar
    @src = compile(string)
  end

  # Compile the mini erb input
  def compile(string)
    buffer, suppress = [], false

    until string.empty?
      text, code, string = string.partition(/<%.*?%>/m)

      text.sub!(/\A$\r?\n?/, "") if suppress
      suppress = false

      buffer << "#{@eoutvar}<<#{text.inspect};" unless text.empty?

      unless code.empty?
        end_point = (suppress = code[-3] == "-") ? -3 : -2

        if code[2] == "="
          buffer << "#{@eoutvar}<<(#{code[3...end_point]}).to_s;"
        else
          buffer << "#{code[2...end_point]};"
        end
      end
    end

    @eoutvar + "='';" + buffer.join + @eoutvar
  end

  # Return the mini erb text with embedded Ruby results.
  def result(evaluator)
    evaluator.eval(@src)
  end

  # Generate results and print them.
  def run(evaluator)
    print result(evaluator)
  end

end
