require_relative "mini_erb/version"

# A simplified, streamlined erb replacement.
class MiniErb

  # The Ruby code generated by mini erb.
  attr_reader :src

  # Create a mini_erb object
  def initialize(string, safe_level=nil, _=nil, eoutvar='_erbout')
    @safe_level, @eoutvar = safe_level, eoutvar
    @src = compile(string)
  end

  # Compile the mini erb input
  def compile(string)
    buffer, suppress = [], false

    until string.empty?
      text, code, string = string.partition(/<%.*?%>/m)

      text.sub!(/\A$\r?\n?/, "") if suppress
      suppress = false

      buffer << "#{@eoutvar}<<#{text.inspect};" unless text.empty?

      unless code.empty?
        end_point = (suppress = code[-3] == "-") ? -3 : -2

        unless code[2] == "#"
          if code[2] == "="
            buffer << "#{@eoutvar}<<(#{code[3...end_point]}).to_s;"
          else
            buffer << "#{code[2...end_point]};"
          end
        end
      end
    end

    @eoutvar + "='';" + buffer.join + @eoutvar
  end

  # Return the mini erb text with embedded Ruby results.
  def result(evaluator = new_toplevel)
    if @safe_level
      proc {$SAFE = @safe_level; evaluator.eval(@src)}.call
    else
      evaluator.eval(@src)
    end
  end

  # Generate results and print them.
  def run(evaluator = new_toplevel)
    print result(evaluator)
  end

private

  # Get a duplicate of the default binding if none is specified.
  def new_toplevel
    TOPLEVEL_BINDING.dup
  end
end
